spring.application.name=nha-khoa-backend
spring.datasource.url=jdbc:mysql://localhost:3306/Nha_khoa?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
jwt.secret=5e52a0519447e04f112a108e69509b1e168c41b427bde6bd47c0506250b59778